length_in_x: 3
length_in_y: 3
position_x: 0.0
position_y: 0.0
resolution: 0.05
min_variance: 0.00001
max_variance: 0.0001
mahalanobis_distance_threshold: 2.5
multi_height_noise: 1e-6
# enable_continuous_cleanup: true